{% set name = "testflows.asserts" %}
{% set version = "6.3.210831.1135705" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/testflows.asserts-{{ version }}.tar.gz
  sha256: a4f4dfe08506bbbfff0de4645d4189fcab752eec172d759172cff795ed440a9c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - testflows.asserts
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/testflows/testflows-asserts
  summary: TestFlows - Asserts Assertion Library
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asford
