{% set name = "testflows.asserts" %}
{% set version = "6.3.210714.1191517" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/testflows.asserts-{{ version }}.tar.gz
  sha256: 4f4ce7a77aeeb6a7356219aad9aae9f815a9f9701d0d642432e5a963f247effb

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - testflows.asserts
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/testflows/testflows-asserts
  summary: TestFlows - Asserts Assertion Library
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asford
