{% set name = "testflows.asserts" %}
{% set version = "6.4.211221.1165422" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/testflows.asserts-{{ version }}.tar.gz
  sha256: ba369fecb870834fec2ddffbb3f7277d2f8f8c9b6b073f2dbab82bb848ec885a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - testflows.asserts
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/testflows/testflows-asserts
  summary: TestFlows - Asserts Assertion Library
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asford
