{% set name = "testflows.asserts" %}
{% set version = "6.5.230626.1133416" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/testflows.asserts-{{ version }}.tar.gz
  sha256: 509bc0f7801a6e9ada8fdb7e4df878fc1e5900ff5284a762517b6b7566b2bb30

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - testflows.asserts
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/testflows/testflows-asserts
  summary: TestFlows - Asserts Assertion Library
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asford
